const GITHUB_TOKEN = process.env.GITHUB_TOKEN
const REPOS = {
  atsell: 'JacobChee/atsell-website',
  afix: 'JacobChee/afix-repo',
}

async function ghFetch(path, options = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `token ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'User-Agent': 'marketing-team-app',
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
  return res.json()
}

export async function POST(req) {
  const { repo, path, content, message, currentSha } = await req.json()
  const repoFull = REPOS[repo]
  if (!repoFull) return Response.json({ error: 'Unknown repo' }, { status: 400 })

  // Get default branch
  const repoData = await ghFetch(`/repos/${repoFull}`)
  const defaultBranch = repoData.default_branch || 'main'

  // Get default branch SHA
  const refData = await ghFetch(`/repos/${repoFull}/git/ref/heads/${defaultBranch}`)
  const baseSha = refData.object?.sha
  if (!baseSha) return Response.json({ error: 'Could not get branch SHA' }, { status: 500 })

  // Create new branch
  const branchName = `team/${Date.now()}-${path.replace(/[^a-z0-9]/gi, '-').slice(0, 30)}`
  await ghFetch(`/repos/${repoFull}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  })

  // Commit file to new branch
  const encoded = Buffer.from(content).toString('base64')
  const body = { message, content: encoded, branch: branchName }
  if (currentSha) body.sha = currentSha

  const commitData = await ghFetch(`/repos/${repoFull}/contents/${path}`, {
    method: 'PUT',
    body: JSON.stringify(body),
  })

  if (commitData.content?.sha === undefined && !commitData.commit) {
    return Response.json({ error: commitData.message || 'Commit failed' }, { status: 500 })
  }

  // Create PR
  const pr = await ghFetch(`/repos/${repoFull}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title: message,
      head: branchName,
      base: defaultBranch,
      body: `Auto-generated by marketing team agent.\n\nFile: \`${path}\``,
    }),
  })

  return Response.json({ ok: true, pr_url: pr.html_url, pr_number: pr.number, branch: branchName })
}
